apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit
spec:
  selector:
    matchLabels:
      app: gerrit # This has to match labels of template below
  replicas: 1
  template:
    metadata:
      labels:
        app: gerrit # This has to match matchLabels above
    spec:
      containers:
      - name: gerrit
        image: gerritcodereview/gerrit
        ports:
        - containerPort: 8080
