apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins # This has to match labels of template below
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins # This has to match matchLabels above
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        # resources:
          # requests:
            # cpu: 100m
            # memory: 100Mi
        env:
        - name: JENKINS_HOST
          value: host_something
        ports:
        - containerPort: 8080
