apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 2Gi
  volumeMode: filesystem
  accessModes:
    - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Retain
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
  hostPath:
    path: "/data/jenkins" # Path on node (minikube - use 'minikube ssh' to get into minikube)