apiVersion: v1
kind: Service
metadata:
  name: gerrit-service
  labels:
    app: gerrit
spec:
  selector:
    app: gerrit
  type: NodePort
  ports:
  - nodePort: 30081 # node
    port: 8080 # pod
    protocol: TCP
    targetPort: 8080 # container: actual port
