apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - nodePort: 30080 # node
    port: 8080 # pod
    protocol: TCP
    targetPort: 8080 # container: actual port
